# 1. Create a 3x3x3 array with random values 

In [56]:
import numpy as np
from numpy import random 
a=np.random.randint(100,size=(5,5,5))
a

array([[[62, 23, 83, 20, 78],
        [47, 60, 61, 23,  9],
        [93, 82,  7, 46, 77],
        [94, 22, 63, 57, 93],
        [70, 14, 21, 93, 98]],

       [[88, 30, 77, 60, 33],
        [37, 50, 60, 18, 44],
        [11, 88, 67, 16,  0],
        [45, 36, 22, 73, 86],
        [33, 20, 76, 91, 24]],

       [[96, 18, 84, 81, 36],
        [46, 37, 47, 78, 37],
        [ 3, 28, 32, 69, 55],
        [ 5, 95, 14, 37, 51],
        [ 6, 63, 11,  9, 95]],

       [[13, 97, 83, 78, 34],
        [73, 60, 76, 43, 16],
        [29, 45, 68, 26, 87],
        [ 6, 96, 91,  1, 48],
        [50, 46, 90, 28, 93]],

       [[13, 40,  6, 48, 57],
        [45, 59, 74, 53, 73],
        [61, 24, 26, 82, 89],
        [96, 13, 45, 81, 71],
        [20, 79, 45, 26,  6]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [14]:
a=np.diag(([1,2,3,4]),-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [20]:
x = np.zeros((8, 8), dtype = int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [58]:
a=np.random.randint(100,size=(5,5))
print('Before normalize')
print(a)
print()
xmin,xmax=a.min(),a.max()
a=(a-xmin)/(xmax-xmin)
print('After Normalize')
print(a)

Before normalize
[[ 6 32 81 12 47]
 [ 0 14 19 49 67]
 [54 46 90 25 57]
 [91 46 41 54 38]
 [62 54 24 61 73]]

After Normalize
[[0.06593407 0.35164835 0.89010989 0.13186813 0.51648352]
 [0.         0.15384615 0.20879121 0.53846154 0.73626374]
 [0.59340659 0.50549451 0.98901099 0.27472527 0.62637363]
 [1.         0.50549451 0.45054945 0.59340659 0.41758242]
 [0.68131868 0.59340659 0.26373626 0.67032967 0.8021978 ]]


# 5.  How to find common values between two arrays?

In [41]:
a=[1,2,3,4,5,6,7,8,9,10]
b=[1,2,34,5,6]
print(np.intersect1d(a,b))

[1 2 5 6]


# 6.How to get the dates of yesterday, today and tomorrow?

In [42]:
from datetime import datetime, timedelta
presentday = datetime.now() # or presentday = datetime.today() 
yesterday = presentday - timedelta(1) 
tomorrow = presentday + timedelta(1) 
print("Yesterday = ", yesterday.strftime('%d-%m-%Y')) 
print("Today = ", presentday.strftime('%d-%m-%Y')) 
print("Tomorrow = ", tomorrow.strftime('%d-%m-%Y')) 

Yesterday =  25-07-2020
Today =  26-07-2020
Tomorrow =  27-07-2020


# 7. Consider two random array A and B, check if they are equal

In [59]:
a=np.random.randint(100,size=(5,5))

a.sort()
b.sort()
if a.any()==b.any() is False:
    print('equal')
else:
    print(' not equal')

 not equal


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [65]:
a=np.random.randint(100,size=(10))
print(a)
xmax=a.max()
print()
print(xmax)
print()
for i in range(10):
    if a[i]==xmax :
        a[i]=0
print(a)

[49 38 45 54 45 83 79 40 53 28]

83

[49 38 45 54 45  0 79 40 53 28]


# 9. How to print all the values of an array?

In [67]:
a=np.random.randint(100,size=(5,5))

print(a)

[[31 39 89 84 34]
 [58 66 90  2 66]
 [80 45 42 73 86]
 [ 3 80 54 80 73]
 [ 8 93  5 65 61]]


# 10.Subtract the mean of each row of a matrix

In [68]:
x=[1,2,3,4]
a=.mean()
a

AttributeError: 'list' object has no attribute 'mean'

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

# 12.How to get the diagonal of a dot product?

# 13.How to find the most frequent value in an array?

# 14.How to get the n largest values of an array

# 15.How to create a record array from a regular array?